# See https://docs.getdbt.com/reference/resource-properties/data-tests

version: 2

models:
  - name: addresses_silver
    description: "addresses"
    columns:
      - name: company_id
        description: "Company"
        data_tests:
          - not_null
      - name: address
        description: "Address"
        data_tests:
          - not_null
      - name: total_spend
        description: "Total Spend"
        data_tests:
          - not_null
      - name: city
        description: "Derived city from address"
        data_tests:
          - not_null

  - name: cities_silver
    description: "cities"
    columns:
      - name: city
        description: "City"
        data_tests:
          - unique
          - not_null
